#!/usr/bin/env fish
if echo $argv[1] | grep -e '--edit' > /dev/null
    open (status --current-filename)
    exit
end

if echo $argv[1] | grep -e '--type' > /dev/null
    mdls -name kMDItemContentTypeTree "$argv[2]"
    exit
end

if not which duti > /dev/null
    brew install duti
end


set editor (osascript -e 'id of app "Macvim"')

function associate
    echo -ne $argv[1]:\t
    duti -vs "$editor" $argv[1] all
end

associate net.daringfireball.markdown
associate org.vim.cfg-file
associate public.c-plus-plus-source
associate public.c-source
associate public.c-header
associate public.data
associate public.plain-text
associate public.python-script
associate public.ruby-script
associate public.script
associate public.shell-script
associate public.source-code
associate public.text
associate public.yaml

associate c
associate cpp
associate dot
associate erb
associate go
associate h
associate jsx
associate py
associate rake
associate rb
associate snippets
associate pgsql
associate nfo
