#!/usr/bin/env python2
import sys
import inflection
import argparse



def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-l', '--left', type=str, default='')
    parser.add_argument('-r', '--right', type=str, default='')
    parser.add_argument('--left-only', action='store_true', default=False)
    args = parser.parse_args()

    lines = [l for l in sys.stdin.read().split('\n')]

    out = []

    for line in lines:
        if line:
            out.append(''.join(assign_to_struct(line, args.left, args.right, args.left_only)))

    print '\n'.join(out)

def assign_to_struct(line, left, right, left_only):
    parts = line.split(' ')
    if not len(parts):
        return ''
    else:
        name = parts[0].strip()
        if left_only:
            return [left, name, ',']
        else:
            return [left, name, ' = ', right,
                    inflection.camelize(name, uppercase_first_letter=False)]

if __name__ =='__main__':
    main()

