#!/usr/local/bin/fish

# remove old .class files
for file in (gfind . -regextype posix-extended -regex '^.*\.class')
	rm $file
end

# compile new ones
for file in (gfind . -regextype posix-extended -regex '^.*\.java')
	echo $file
	javac $file
end
	
	

# launch jvm with first argument to this script
set arg $argv[1]
set name (echo $arg | sed 's/.java// ; s/.class//')
java $name






