#!/usr/bin/env fish
if git diff --quiet
    set branch (git rev-parse --abbrev-ref HEAD)
    git checkout development
    git fetch origin
    git rebase origin/development
    git checkout $branch
    git rebase development
else
    echo commit your changes
end
