#!/usr/bin/env python3
import sys
import argparse

try:
    import inflection
except ImportError:
    sys.exit("pip install inflection")

INFLECTIONS = [
    "camelize",
    "dasherize",
    "humanize",
    "ordinal",
    "ordinalize",
    "parameterize",
    "pluralize",
    "singularize",
    "tableize",
    "titleize",
    "underscore",
]


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("inflection", nargs=1, choices=INFLECTIONS)
    return parser.parse_args()


def main():
    args = get_args()
    fn = getattr(inflection, args.inflection[0])
    print(fn(sys.stdin.read()))


if __name__ == "__main__":
    main()
