#!/usr/bin/env python3
import sys

try:
    from netifaces import interfaces, ifaddresses
except ImportError:
    sys.exit('pip install netifaces')

def interesting(address):
    return ':' not in address and address not in {'127.0.0.1', 'no addr'}


for interface in interfaces():
    for key, val in ifaddresses(interface).items():
        address = val[0].get('addr', 'no addr')
        if interesting(address):
            print(interface, address)



        

