#!/usr/bin/osascript

on run argv
	-- cli_alert(argv)
	set command to ""
	set command to join(argv, " ")

	launch "iTerm"
	tell application "iTerm"
		-- activate
	
		tell the first terminal
			launch session "Default"
			tell the last session
				write text command
			end tell
		end tell
	end tell
end run

on join(a_list, seperator)
	set AppleScript's text item delimiters to seperator
	return "" & a_list
end join

on cli_alert(the_alert)
	set len to count of the_alert
	if len > 0 then
		tell application "SystemUIServer"
			display dialog the_alert
		end tell
	end
end cli_alert
