#!/usr/bin/env python3
import sys
import os
import json
try:
    import msgpack
except ImportError:
    sys.exit('pip install msgpack-python')

input_json = sys.stdin.read()
objects = json.loads(input_json)
binary = msgpack.packb(objects)
sys.stdout.buffer.write(binary)
