#!/usr/bin/env python2
from __future__ import print_function
import sys
from simplejson import loads, dumps, JSONDecodeError

data = sys.stdin.read()
try:
    pretty = dumps(loads(data), sort_keys=True, indent=4, separators=(',', ': '))
    print(pretty)
except JSONDecodeError, e:
    line = data.split('\n')[e.lineno]
    error_marker = ''.join(['^' if i == e.colno else '-' for i, c in enumerate(line)])
    print(line)
    print(error_marker)
    print(e, file=sys.stderr)
    sys.exit(71)


