#!/usr/bin/env python3
import sys
import json
try:
    import msgpack
except ImportError:
    sys.exit('pip install msgpack-python')

def traverse(data, fn=None):
    if isinstance(data, (list, tuple)):
        return [traverse(d, fn=fn) for d in data]
    elif isinstance(data, dict):
        return {traverse(k, fn=fn): traverse(v, fn=fn) for k, v in data.items()}
    else:
        try:
            return fn(data)
        except:
            return data


objects = traverse(msgpack.unpack(sys.stdin.buffer), fn=lambda b: b.decode('utf-8'))
pretty = json.dumps(objects)
print(pretty)
