#!/usr/bin/env python2
import sys
import msgpack
import json

data = sys.stdin.read()
objects = msgpack.unpackb(data)
pretty = json.dumps(objects, sort_keys=True, indent=4, separators=(',', ': '))
print(pretty)

