#!/usr/bin/env python3
import sys

def main():
    raw = sys.stdin.read()
    for line in raw.split('\n'):

def parse_line(line):
    arity = {
            'M': 2,
            'L': 2,
            'V': 1,
            'C': 
            'S':
            'Q':
            'T':
            'A':
            'Z': 1,
    }
    formats = {
            3: '{}{} {}',
            2: '{} {}',
            1: '{}',
    }

    parts = line.split(' ')
    
    arity = commands.get(parts[0].upper(), 0)
    



