#!/usr/bin/env fish
if [ -e ./cert.pem ]; and [ -e ./key.pem ]
else
    echo "Generate a key and cert with:"
    echo "openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes"
    echo "and add the cert to keychain before proxying"
    exit 1
end

set conf_file (mktemp "/tmp/proxy-"(uuid)".conf")

set IFS ''
echo "daemon off;
master_process off;

error_log /dev/stdout;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    server {
        listen 80;
        location / {
            proxy_set_header Host \$host;
            proxy_pass http://127.0.0.1:3000;
        }
    }
    server {
        listen 443 ssl;
        ssl_certificate "(pwd)"/cert.pem;
        ssl_certificate_key "(pwd)"/key.pem;
        location / {
            proxy_set_header Host \$host;
            proxy_pass http://127.0.0.1:3000;
        }
    }
}" > "$conf_file"
echo "$conf_file"
nginx -c "$conf_file"

rm "$conf_file"
