#!/usr/bin/env python3 -u
from itertools import product
import sys
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-w', '--wordsonly', action='store_true', default=False)
    parser.add_argument('--min_length', action='store', default=None, type=int)
    parser.add_argument('--max_length', action='store', default=None, type=int)
    parser.add_argument('string_to_permute', nargs='?', default=None)
    args = parser.parse_args()

    string_to_permute = args.string_to_permute or sys.stdin.read()

    if args.wordsonly:
        with open('/usr/share/dict/words') as wordlist:
            filter_set = {line.strip().lower() for line in wordlist}
    else:
        filter_set = None

    min_length = args.min_length or len(string_to_permute)
    max_length = args.max_length or len(string_to_permute)

    for length in range(min_length, max_length + 1):
        for perm in product(string_to_permute, repeat=length):
            word = ''.join(perm)

            if not filter_set:
                print(word)
            elif word in filter_set:
                print(word)


if __name__ == '__main__':
    main()
