#!/usr/bin/env python3
from itertools import permutations
import sys
import argparse

def main()
    parser = argparse.ArgumentParser()
    parser.add_argument('-w', '--wordsonly', action='store_true', default=False)
    parser.add_argument('string_to_permute', nargs='?', default=None)
    args = parser.parse_args()
    
    string_to_permute = args.string_to_permute or sys.stdin.read()

    if args.wordsonly:
        with open('/usr/share/dict/words') as wordlist:
            filter_set = {line.strip().lower() for line in wordlist}
    else:
        filter_set = None

    for perm in permutations(string_to_permute):
        word = ''.join(perm)
        if not filter_set:
            print(word)
        elif word in filter_set:
            print(word)

if __name__ == '__main__':
    main()
