#!/usr/bin/env fish

if [ 2 -eq (count $argv) ]
    set MATCH "$argv[1]"
    set REGEX "$argv[2]"
else if [ 1 -eq (count $argv) ]
    set MATCH "$argv[1]"
    set REGEX ""
else
    echo "Usage pie [ACK SEARCH REGEX] [PERL MODIFICATION REGEX]"
    exit
end


set matched_files (ack "$MATCH" | nocolor | cut -d : -f 1 | sort -u | sed '/^\s*$/d')
set matched_files_count (count $matched_files)

echo (color -f red "Search regex $MATCH matches $matched_files_count files")

if [ -z "$REGEX" ]
    echo "No modification regex, exiting"
    exit
end

for i in (seq 1 $matched_files_count)
    echo $matched_files[$i]
    perl -pi -e "$REGEX" $matched_files[$i]
end





