#!/usr/bin/env python3
import sys
import os
from IPython import embed

try:
    import plexapi.myplex
except ImportError:
    sys.exit("pip install plexapi")

username = os.environ['PLEX_USERNAME']
password = os.environ['PLEX_PASSWORD']
server_name = os.environ['PLEX_SERVER']

print(f'authenticating {username}')
account = plexapi.myplex.MyPlexAccount(username, password)

print(f'connecting to {server_name}')
server = account.resource(server_name).connect()

print(f'searching {server}')
section = next(s for s in server.library.sections() if s.title == 'Youtube')
watched_items = section.search(unwatched=False)

if not watched_items:
    print('nothing to delete')

for item in watched_items:
    print(f'deleting {item}')
    item.delete()

print('done')
