#!/usr/bin/env fish
set -g -x last_status $status

echo -n (set_color purple)(current-time)\
" "(set_color blue)(whoami)(set_color white)"@"(set_color cyan)(hostname)\
" "(set_color red)(virtual-env-name)\
(set_color yellow)(current-branch)\
(set_color green)(prompt_pwd)\
" "(set_color blue)">"" "\
