#!/usr/bin/env fish
set -g -x last_status $status

set ARROW ''

set_color $base0
set_color -b $base02
echo -n (current-time)

set_color $base02
set_color -b $blue
echo -n $ARROW' '

set_color $base3
echo -n (whoami)"@"(hostname)' '

set_color $blue
set_color -b $base0
echo -n $ARROW

set_color $base03
echo -n (current-branch)

set_color $base0
set_color -b $green
echo -n $ARROW' '

set_color white -o
set_color -b $green
echo -n (prompt_pwd)

set_color -b normal
set_color $green
echo -n $ARROW' '

set_color normal
