#!/usr/bin/env python

from sys import argv

def frange(start, stop, step):
    lst = []
    if step > 0:
        while start < stop:
            lst.append(start)
            start += step
    elif step < 0:
        while stop < start:
            lst.append(start)
            start += step
    return lst

def main():
    start = float(argv[1])
    stop = float(argv[2])
    if (start == 0) and (stop == 0):
        return
    if len(argv) == 4:
        step = float(argv[3])
    else:
        step = int(-(start - stop)/abs(start - stop))
    print(' '.join(str(n) for n in frange(start, stop, step)))

if __name__ == '__main__':
    main()
