#!/usr/bin/env python3
import socket
import sys
from time import sleep
from datetime import datetime

def can_resolve(host):
    try:
        socket.gethostbyname(host)
        return True
    except socket.gaierror:
        return False

def wait_until_resolved(host, after_failure=None, after_success=None):

    while not can_resolve(host):
        after_failure() if after_failure else None
        sleep(10)

    after_success() if after_success else None



def main():
    host = sys.argv[1]

    start = datetime.now()
    checks = []

    def after_failure():
        checks.append(1)
        print('Can not resolve %s. Sleeping' % host)

    def after_success():
        if len(checks) == 0:
            print('Resolved the first time')
        else:
            print('Waited %s to resolve. % checks' % ((datetime.now() - start), checks))


    wait_until_resolved(host, after_failure, after_success)

if __name__ == '__main__':
    main()

