#!/usr/bin/env ruby
require 'json'

# Expression      Result
# {}.a            nil
# {a: 1}.a        1
# {'a' => 1}.a    1
# {}.a!           NoMethodError  force an error if the thing does not implement that method
class Hash
  def method_missing(method, *_args)
    return self[method] if key?(method) # indifferent access

    name = method.to_s

    return self[name] if key?(name)

    return send(name.slice(0, name.length).to_sym) if name.end_with?('!')

    nil
  end
end

d = data = JSON.parse(STDIN.read)

result = binding.eval('data' + ARGV.join(' '))

puts JSON.pretty_generate(result)
