#!/usr/bin/env ruby
require 'json'
class Symbol
  def to_proc
    proc do |maybe_hash|
      if maybe_hash.is_a?(Hash)
        if maybe_hash.key?(self)
          maybe_hash[self]
        elsif maybe_hash.key?(to_s)
          maybe_hash[to_s]
        end
      else
        super
      end
    end
  end
end

d = data = JSON.parse(STDIN.read)

context = (proc {}).binding

result = context.eval(ARGV.join(' '))

puts JSON.pretty_generate(result)
