#! /usr/bin/env python
# -*- coding: utf-8 -*-
import cherrypy
from cherrypy.lib.static import serve_file
import glob
import sys, os, subprocess

def main():
	if get_arg(['-h', '--help'], False):
		print usage
		sys.exit(64)
	port = get_arg(['-p','--port'], 8080)
	directory = get_arg(['-d','--directory'], '.')

	cherrypy.config.update({'server.socket_port': port})
	cherrypy.config.update({'server.socket_host': get_current_addr()})
	os.chdir(directory)

	files = Files()
	files.download = Download()
	cherrypy.quickstart(files)

def get_arg(flags, default):
	for flag in flags:
		if flag in sys.argv:
			index = sys.argv.index(flag)
			if type(default) is bool:
				return not default
			else:
				if type(default) is str:
					return sys.argv[index+1]
				else:
					return eval(sys.argv[index+1])
	return default

def get_current_addr():
	ip = '127.0.0.1'
	if 'darwin' in sys.platform:
		out = subprocess.Popen(['ipconfig', 'getifaddr', 'en1'], stdout=subprocess.PIPE)
		ip = out.stdout.readlines()[0].strip()
	return ip

	

class Files:
	def index(self, directory='.'):
		html = u"""<html><body><h2>Files in %s</h2>
				<a href="index?directory=%s" >↩</a><br />
				""" % (directory,os.path.dirname(os.path.abspath(directory)))
		for filename in glob.glob(directory + '/*'):
					absPath = os.path.abspath(filename)
					if os.path.isdir(absPath):
						html += '<a href="/index?directory=' + absPath + '">' + os.path.basename(filename) + "</a> <br />"
					else:
						html += '<a href="/download/?filepath=' + absPath + '">' + os.path.basename(filename) + "</a> <br />"

		html += """</body></html>"""
		return html
	index.exposed = True

class Download:
	def index(self, filepath):
		return serve_file(filepath, "application/x-download", "attachment")
	index.exposed = True



if __name__ == '__main__':
	main()