#!/usr/bin/env python3
import sys

stdin = ''.join([line for line in sys.stdin])
unescaped = stdin.encode('utf8').decode('unicode-escape')
unescaped = unescaped[1:-1] if unescaped.startswith('"') and unescaped.endswith('"') else unescaped
print(unescaped)
