#!/usr/bin/env python2
from __future__ import print_function, unicode_literals
import sys

try:
    import jsbeautifier
except ImportError as e:
    print('pip install jsbeautifier')
    sys.exit(0)

options = jsbeautifier.default_options()
options.jslint_happy = True
options.wrap_line_length = 75

print(jsbeautifier.beautify(sys.stdin.read()))
