#!/usr/bin/env python3
import sys

try:
    import jsbeautifier
except ImportError as e:
    print('pip install jsbeautifier')
    sys.exit(0)

options = jsbeautifier.default_options()
options.jslint_happy = True
options.wrap_line_length = 75

print(jsbeautifier.beautify(sys.stdin.read()))
