#!/usr/bin/env fish
set fish_trace 1


curl -L 'https://plex.tv/downloads/latest/5?channel=16&build=linux-x86_64&distro=debian' > ~/plex-latest.deb

sudo dpkg --install ~/plex-latest.deb

rm ~/plex-latest.deb
