#!/usr/bin/env ruby
require 'open3'
require 'rollbar'

def torrent_dir
  ENV.fetch('TR_TORRENT_DIR')
end

def torrent_name
  ENV.fetch('TR_TORRENT_NAME')
end

def torrent_path
  "#{torrent_dir}/#{torrent_dir}"
end

def with_reporting
  yield
rescue StandardError => e
  Rollbar.error(e)
end

def upload
  Rollbar.info("started upload", torrent_name: torrent_name)
  Open3.popen3("~/dropbox_uploader.sh upload #{torrent_path} #{torrent_name}")
  Rollbar.info("finished upload", torrent_name: torrent_name)
end

def configure_rollbar
  Rollbar.configure do |config|
    config.access_token = ENV.fetch('ROLLBAR_ACCESS_TOKEN')
  end
end


