#!/usr/bin/env fish

set running (vboxmanage list runningvms) > /dev/null
if echo "$running" | grep 'dev'
    # nothing, machine is running
else
    vboxmanage startvm dev --type headless
    while not ping -c 1 local.instaedu.com > /dev/null
        sleep 2
    end
end

ssh instaedu@local.instaedu.com $argv
