#!/usr/bin/env fish
if [ ! -e ~/.vim/bundle/Vundle.vim ]
    mkdir -p ~/.vim/bundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
end

vim +PluginClean! +PluginInstall +qall
