#!/usr/bin/env python3
import sys
import datetime
import socket
from time import sleep

def wait_for_dns(message_fn, host):
    sleep_time = 2
    def able_to_resolve(host):
        try:
            socket.gethostbyname(host)
            return True
        except socket.gaierror:
            return False

    start = datetime.datetime.now()
    checks = 1
    while not able_to_resolve(host):
        checks += 1
        message_fn('Unable to resolve %s. Sleeping for %s seconds.' % (host, sleep_time))
        sleep(sleep_time)

    if checks > 1:
        message_fn('Waited %s for DNS to resolve. (%s checks)' % ((datetime.datetime.now() - start), checks))

if __name__ == '__main__':
    try:
        wait_for_dns(print, sys.argv[1])
    except KeyboardInterrupt as e:
        print('exiting.')
        sys.exit(0)
