#!/usr/bin/env python3
import yt_dlp

options = {
    'format': 'bestvideo[vcodec!*=av01]+bestaudio[acodec!*=opus]',
    'merge-output-format': 'mkv',
    'outtmpl': '%(uploader)s-%(title)s-%(id)s.%(ext)s',
    'cookies': './cookies.txt',
}

with yt_dlp.YoutubeDL(options) as y:
    y.download(['https://www.youtube.com/playlist?list=WL'])
