#!/usr/bin/env python3
import requests

import inspect

try:
    import papirus
except ImportError:
    papirus = None

latitude = '45.489938'
longitude = '-122.690453'

session = requests.Session()
session.headers.update({'User-Agent': 'nicks-weather-script'})
# https://www.weather.gov/documentation/services-web-api


def forecast_url(latitude, longitude):
    response = session.get(
        f'https://api.weather.gov/points/{latitude},{longitude}')
    response.raise_for_status()
    return response.json()['properties']['forecast']


def forecasts():
    response = session.get(forecast_url(latitude, longitude))
    response.raise_for_status()
    return response.json()['properties']['periods']


def forcast_str(forecast):
    return inspect.cleandoc(f'''
    {forecast['name']}: {forecast['temperature']}{forecast['temperatureUnit']} {forecast['windSpeed']}
    {forecast['detailedForecast']}
    ''')


if papirus:
    screen = papirus.PapirusTextPos()

    def printer(string):
        screen.Clear()
        screen.AddText(string)
        screen.WriteAll()
        print(string)
else:
    def printer(string):
        print(string)

output = '\n'.join([forcast_str(f) for f in forecasts()[:2]])
printer(output)
