#!/usr/bin/osascript

on run argv
    tell application "Mail"
        set x to enabled of account "slalom"
        set enabled of account "slalom" to not x
    end tell
    
    tell application "Mail"
        set x to enabled of account "microsoft"
        set enabled of account "microsoft" to not x
    end tell
end run