#!/usr/bin/env python3
import sys
import argparse
import json

import pyaml

try:
    import yaml
except ImportError:
    sys.exit('pip install PyYAML')


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-j', '--to-json', '--json',
                        action='store_true', default=False)

    parser.add_argument('file_path', nargs="?", default=None)

    args = parser.parse_args()

    if args.to_json:
        def dump(data):
            return json.dumps(data,
                              ensure_ascii=True,
                              sort_keys=True,
                              indent=4,
                              separators=(',', ': '))

    else:
        def dump(data):
            return pyaml.dump(data)

    if args.file_path:
        data_file = open(args.file_path, 'r')
    else:
        data_file = sys.stdin

    try:
        loaded = yaml.safe_load(data_file.read())
        print(dump(loaded))
    except yaml.parser.ParserError as e:
        print(e, file=sys.stderr)
        sys.exit(71)


if __name__ == '__main__':
    main()
