#!/usr/bin/env python3
import sys
import argparse
import json

try:
    import yaml
except ImportError:
    sys.exit('pip install PyYAML')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-j', '--to-json', action='store_true', default=False)
    args = parser.parse_args()

    if args.to_json:
        def dump(data):
            return json.dumps(data,
                              ensure_ascii=True,
                              sort_keys=True,
                              indent=4,
                              separators=(',', ': '))

    else:
        def dump(data):
            return yaml.dump(data,
                             default_flow_style=False)

    try:
        loaded = yaml.safe_load(sys.stdin.read())
        print(dump(loaded))
    except yaml.parser.ParserError as e:
        print(e, file=sys.stderr)
        sys.exit(71)


if __name__ == '__main__':
    main()
